Add support for static completions with __vagrant_static_completion flag

diff --git a/etc/bash_completion.d/vagrant b/etc/bash_completion.d/vagrant
--- a/etc/bash_completion.d/vagrant
+++ b/etc/bash_completion.d/vagrant
@@ -27,6 +27,9 @@
 # ensure vagrant is on the PATH
 hash vagrant &>/dev/null && {
 
+# static completions are much faster but less accurate
+__vagrant_static_completion=1
+
 __vagrant_complete(){
     local command_options=''
 
@@ -99,18 +102,95 @@ __vagrant_get_environments(){
     echo "$vagrant_environments"
 }
 
-__vagrant_get_nonrunning_vms(){
+__vagrant_get_not_off(){
 
-    local vagrant_output='' vagrant_vms=''
+    local not_off='' reply=''
+
+    not_off=$(__vagrant_get_not_off_local)
+
+    reply=$?
+
+    if (( reply == 1 )); then
+        return 1
+    elif (( reply == 100 )); then
+        not_off=$(__vagrant_get_not_off_global) || return 1
+    fi
+
+    echo "$not_off"
+}
+
+__vagrant_get_not_off_global(){
+
+    local not_off='' vagrant_output=''
 
     # local must be declared beforehand in order to return an accurate exit status here
-    vagrant_output=$(vagrant status 2>/dev/null) || return 1
+    vagrant_output=$(vagrant global-status 2>/dev/null) || return 1
 
-    vagrant_vms=$(awk '/^$/ {while (getline && NF != 0) if ($2 != "running") print $1}' <<<"$vagrant_output")
+    not_off=$(awk '/^-+$/ {while (getline && NF != 0) if ($4 != "poweroff") print $1}' <<<"$vagrant_output")
 
-    [[ -z $vagrant_vms ]] && return 1
+    [[ -z $not_off ]] && return 1
 
-    echo "$vagrant_vms"
+    echo "$not_off"
+}
+
+__vagrant_get_not_off_local(){
+
+    local not_off='' vagrant_output=''
+
+    # local must be declared beforehand in order to return an accurate exit status here
+    vagrant_output=$(vagrant status 2>/dev/null) || return 100
+
+    not_off=$(awk '/^$/ {while (getline && NF != 0) if ($2 != "poweroff") print $1}' <<<"$vagrant_output")
+
+    [[ -z $not_off ]] && return 1
+
+    echo "$not_off"
+}
+
+__vagrant_get_not_running(){
+
+    local not_running='' reply=''
+
+    not_running=$(__vagrant_get_not_running_local)
+
+    reply=$?
+
+    if (( reply == 1 )); then
+        return 1
+    elif (( reply == 100 )); then
+        not_running=$(__vagrant_get_not_running_global) || return 1
+    fi
+
+    echo "$not_running"
+}
+
+__vagrant_get_not_running_global(){
+
+    local not_running='' vagrant_output=''
+
+    # local must be declared beforehand in order to return an accurate exit status here
+    vagrant_output=$(vagrant global-status 2>/dev/null) || return 1
+
+    not_running=$(awk '/^-+$/ {while (getline && NF != 0) if ($4 != "running") print $1}' <<<"$vagrant_output")
+
+    [[ -z $not_running ]] && return 1
+
+    echo "$not_running"
+}
+
+
+__vagrant_get_not_running_local(){
+
+    local not_running='' vagrant_output=''
+
+    # local must be declared beforehand in order to return an accurate exit status here
+    vagrant_output=$(vagrant status 2>/dev/null) || return 100
+
+    not_running=$(awk '/^$/ {while (getline && NF != 0) if ($2 != "running") print $1}' <<<"$vagrant_output")
+
+    [[ -z $not_running ]] && return 1
+
+    echo "$not_running"
 }
 
 # ignore current word and actions
@@ -123,20 +203,6 @@ __vagrant_get_options(){
     done
 
     return 0
-}
-
-__vagrant_get_running_vms(){
-
-    local vagrant_output='' vagrant_vms=''
-
-    # local must be declared beforehand in order to return an accurate exit status here
-    vagrant_output=$(vagrant status 2>/dev/null) || return 1
-
-    vagrant_vms=$(awk '/^$/ {while (getline && NF != 0) if ($2 != "poweroff") print $1}' <<<"$vagrant_output")
-
-    [[ -z $vagrant_vms ]] && return 1
-
-    echo "$vagrant_vms"
 }
 
 __vagrant_get_snapshots(){
@@ -213,6 +279,25 @@ __vagrant_list_options(){
     echo "${opts[@]}"
 }
 
+__vagrant_print_box_commands(){
+    printf '%s\n' add help list outdated remove repackage update
+}
+
+__vagrant_print_commands(){
+    printf '%s\n' box connect destroy docker-logs docker-run global-status \
+        halt help init list-commands login package plugin provision push rdp \
+        reload resume rsync rsync-auto share snapshot ssh ssh-config status \
+        suspend up version
+}
+
+__vagrant_print_plugin_commands(){
+    printf '%s\n' install license list uninstall update
+}
+
+__vagrant_print_snapshot_commands(){
+    printf '%s\n' back delete go list take
+}
+
 # accept option as argument and return successfully if option has already been used
 __vagrant_test_option(){
 
@@ -246,10 +331,10 @@ __vagrant(){
 
     if (( ${#words[@]} == 1 )); then
 
-        # DEFAULTS: box connect destroy docker-logs docker-run global-status
-        #           halt help init list-commands login package plugin provision
-        #           push rdp reload resume rsync rsync-auto share ssh ssh-config
-        #           status suspend up version
+        if (( $__vagrant_static_completion == 1 )); then
+            readarray -t COMPREPLY < <(compgen -W "$(__vagrant_print_commands)" -- "$cur")
+            return 0
+        fi
 
         # get vagrant commands only if they are not already cached
         [[ -z $__vagrant_commands ]] && {
@@ -265,7 +350,10 @@ __vagrant(){
         case "$action" in
 
             box)
-                # DEFAULTS: add help list outdated remove repackage update
+                if (( $__vagrant_static_completion == 1 )); then
+                    readarray -t COMPREPLY < <(compgen -W "$(__vagrant_print_box_commands)" -- "$cur")
+                    return 0
+                fi
 
                 # get box commands only if they are not already cached
                 [[ -z $__vagrant_box_commands ]] && {
@@ -315,7 +403,7 @@ __vagrant(){
                 ;;
 
             halt|provision|resume|rsync|rsync-auto|ssh|ssh-config|suspend)
-                local command_options='' running_vm_list=''
+                local command_options='' not_off=''
 
                 case "$action" in
 
@@ -350,14 +438,19 @@ __vagrant(){
 
                 esac
 
-                running_vm_list=$(__vagrant_get_running_vms) || return 1
+                not_off=$(__vagrant_get_not_off) || return 1
 
-                readarray -t COMPREPLY < <(compgen -W "$command_options $running_vm_list" -- "$cur")
+                readarray -t COMPREPLY < <(compgen -W "$command_options $not_off" -- "$cur")
 
                 return 0
                 ;;
 
             help)
+                if (( $__vagrant_static_completion == 1 )); then
+                    readarray -t COMPREPLY < <(compgen -W "$(__vagrant_print_commands)" -- "$cur")
+                    return 0
+                fi
+
                 # get vagrant commands only if they are not already cached
                 [[ -z $__vagrant_commands ]] && {
                     __vagrant_commands=$(__vagrant_get_commands) || return 1
@@ -398,7 +491,10 @@ __vagrant(){
                 ;;
 
             plugin)
-                # DEFAULTS: install license list uninstall update
+                if (( $__vagrant_static_completion == 1 )); then
+                    readarray -t COMPREPLY < <(compgen -W "$__vagrant_print_plugin_commands" -- "$cur")
+                    return 0
+                fi
 
                 # get plugin commands only if they are not already cached
                 [[ -z $__vagrant_plugin_commands ]] && {
@@ -435,7 +531,10 @@ __vagrant(){
                 ;;
 
             snapshot)
-                # DEFAULTS: back delete go list take
+                if (( $__vagrant_static_completion == 1 )); then
+                    readarray -t COMPREPLY < <(compgen -W "$(__vagrant_print_snapshot_commands)" -- "$cur")
+                    return 0
+                fi
 
                 # get snapshot commands only if they are not already cached
                 [[ -z $__vagrant_snapshot_commands ]] && {
@@ -456,12 +555,12 @@ __vagrant(){
                     return $?
                 fi
 
-                local up_options='' nonrunning_vm_list=''
+                local not_running='' up_options=''
 
                 up_options=$(__vagrant_list_options --destroy-on-error --no-destroy-on-error --no-parallel --no-provision --parallel --provider --provision --provision-with)
-                nonrunning_vm_list=$(__vagrant_get_nonrunning_vms) || return 1
+                not_running=$(__vagrant_get_not_running) || return 1
 
-                readarray -t COMPREPLY < <(compgen -W "$up_options $nonrunning_vm_list" -- "$cur")
+                readarray -t COMPREPLY < <(compgen -W "$up_options $not_running" -- "$cur")
 
                 return 0
                 ;;
